### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by DonPage** [timmywil/generator-threejs#5]
running `yo threejs` gives me this error: 
```
/usr/local/lib/node_modules/generator-threejs/node_modules/yeoman-generator/lib/base.js:444
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: Object #<Object> has no method 'on'
    at run (/usr/local/lib/node_modules/generator-threejs/node_modules/yeoman-generator/lib/base.js:444:21)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:330:20)
    at /usr/local/lib/node_modules/yo/lib/cli.js:91:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:66:7)
    at pre (/usr/local/lib/node_modules/yo/lib/cli.js:53:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:155:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by timmywil** [comment]
I think all you need to do is update `yo`. Let me know if that doesn't work.

**Comment by DonPage** [comment]
yo --version is at 1.4.5

**Comment by timmywil** [comment]
There have been similar issues reported to other generators. Your version of yo may have been corrupted by a broken `npm update`. Try `npm install -g yo`?

**Comment by DonPage** [comment]
`npm install -g yo` worked. Thanks.
